#!/usr/bin/env bash
# This script links in the most useful vim plugins from the .vim/available_plugins folder
# script should be run from $HOME/.vim/bundle folder
#
for p in L9 SudoEdit.vim ack align buf_only csv.vim ctrlp.vim delmitmate dirdiff emmet-vim hexman html_autoclose link_plugins nerdcommenter nerdtree powerline quich-filter showmarks source-explorer supertab syntastic tagbar textile.vim toggle_maximize undotree vim-airline vim-autoformat vim-bookmarks vim-closetag vim-coffee-script vim-fugitive vim-jade vim-javascript-syntax vim-json vim-lawrencium vim-misc vim-mustache-handlebars vim-nodejs-complete vim-rails vim-ruby vim-scala vim-session vim-signify vim-surround vim-syntax-redminewiki vim-unimpaired vimball xptemplate yaml python-syntax
do
	echo "Activating plugin --> $p"
	ln -nfs ../available_plugins/$p .
done

